### ISSUE TITLE
Upscale

### ISSUE THREAD

**Issue by fillemazendacus** [rbbrdckybk/dream-factory#10]
Hey!
How that upscale should work?
When I have:
```
!USE_UPSCALE = yes
!UPSCALE_AMOUNT = 2.0
```
  and original is 768x768, should the final result be 1536x1536 (it does not happen)? Or is it about something else?

**Comment by rbbrdckybk** [comment]
Yes, if **!UPSCALE_AMOUNT = 2.0**, you should end up with an image where both dimensions are multiplied by 2.

If you're not seeing that happen, please take a look at your console output - do you see a line that says "Invoking Real-ESRGAN: ..." after each batch of images is completed? Are there any errors?

**Comment by fillemazendacus** [comment]
No error messages:
`Invoking Real-ESRGAN: python inference_realesrgan.py -n RealESRGAN_x4plus --suffix u -s 2.0 -i ..//output/2022-10-19-image/gpu_0 -o ..//output/2022-10-19-image/gpu_0 --face_enhance -g 0`

Next line is already "[cuda:0] >>> finished job #44 in 277.29 seconds." as usual.

**Comment by rbbrdckybk** [comment]
It looks like I'm suppressing errors during upscaling, which in hindsight probably isn't a great idea. How much GPU VRAM do you have? I suspect you might be getting an out-of-memory error during upscaling.

If you're comfortable editing a bit of code, you can verify by opening the **utils.py** file in the **scripts** sub-directory and changing line 791 (if you're on Windows, otherwise skip below for Linux) from:

```
subprocess.call(shlex.split(command), cwd=(cwd + '\Real-ESRGAN'), stderr=subprocess.DEVNULL)
```
to:
```
subprocess.call(shlex.split(command), cwd=(cwd + '\Real-ESRGAN'))
```

If you're on Linux, change line 793 from:
```
subprocess.call(shlex.split(command), cwd=(cwd + '/Real-ESRGAN'), stderr=subprocess.DEVNULL)
```
to:
```
subprocess.call(shlex.split(command), cwd=(cwd + '/Real-ESRGAN'))
```

Make sure to keep the indents intact. That will allow you to see any errors that ESRGAN throws during the upscaling process.

**Comment by fillemazendacus** [comment]
I'm not sure what are indents, but change of line 791 didn't gave any difference. Then, just in case, I changed line 793 same way too with no differences. GPU VRAM is 11127 MB.

**Comment by rbbrdckybk** [comment]
That is very odd. Did you see any errors when you did the initial setup? 

I just added a stand-alone upscale utility that you can use to test ESRGAN to github. Update your installation to get it:
```
python setup.py --update
```
Then run this:
```
cd utils
python upscale.py --imgdir "[full path to directory containing images to upscale]" --amount 2.0
```

Replace **[full path to directory containing images to upscale]** with your path to a directory containing images to upscale.

**Comment by fillemazendacus** [comment]
This worked (although this time not through either update (both anakonda and git bash said update done but nothing new was found) - I had to download "utils" myself and put it in the right place), 512 -> 1024.
Basically with that I have the answer to my interest and this case solved for me. I was curious to see upscale result if it is any better than Topaz Gigapixel AI. Quite similar.
