### ISSUE TITLE
help with AMD 

### ISSUE THREAD

**Issue by FlamingoDelta** [rbbrdckybk/dream-factory#14]
I am using linux (fedora) and need help if there is any way I can test this on an amd video card.

I don't know if there is a way to make it work with rocm

**Comment by rbbrdckybk** [comment]
It should be possible in theory but I haven't tried to get it to work myself. At minimum you'd need rocm, like you mentioned, and then you'd need to [customize your pytorch installation](https://pytorch.org/get-started/locally/) to use rocm (my setup.py install script assumes CUDA, so you'd need to do the pytorch installation manually).

After that, I'm not sure what other step(s) you'd need to take, if any. If you do manage to get it working please let me know!
