### ISSUE TITLE
Not detecting GPU(s)

### ISSUE THREAD

**Issue by Elyssen-1** [rbbrdckybk/dream-factory#15]
GPU: 3080
OS: Win10
Starting up the script it does not detect my GPU at all.
```
python dream-factory.py
[controller] >>> reading configuration from config.txt...
[controller] >>> starting webserver (http://localhost:8080/) as a background process...
[controller] >>> detected 0 total GPU device(s)...
[controller] >>> ERROR: unable to initialize any GPUs for work; exiting!
```

**Comment by MorinTedronai** [comment]
> Heya! This might be an easy fix I'm not smart enough to accomplish and I'm surprised no one got this before or at least asked about it. I have a Strix 3080 10GB. After days of fighting with conda and multiple broken installations now that I have it set up it does not detect my GPU at all. Any logs that help me find out why?
> 
> ```
> python dream-factory.py
> [controller] >>> reading configuration from config.txt...
> [controller] >>> starting webserver (http://localhost:8080/) as a background process...
> [controller] >>> detected 0 total GPU device(s)...
> [controller] >>> ERROR: unable to initialize any GPUs for work; exiting!
> ```

I'm getting the same error but it also seems there was no config file generated in /stable-diffusion after install. Testing on Linux Mint 20.1

**Comment by Pocketsnb** [comment]
Here's what I had to do to get the code running, performed between steps 2 and 3.

1. Install NVIDIAs CUDA for my system, I used the network install after following the workflow.
[CUDA Toolkit 11.8 Downloads](https://developer.nvidia.com/cuda-downloads)


2. Then I installed pytorch. The site has a nice workflow on what conda command to run for your system. And while I had CUDA version 11.8 installed, pytorch-cuda 11.7 seems to work (pytorch-cuda 11.8 is not released yet). It also has some verification steps further down to ensure it installed correctly, and that CUDA is enabled for the GPU.
[PyTorch](https://pytorch.org/get-started/locally/)


That will get you to the point that it detects your graphics card, however, the program continued to fail for me, so I had to perform some additional steps.

3. Added some new channels to conda so I wouldn't have to specify them each time they would be referenced.
```
conda config --env --add channels conda-forge
conda config --env --add channels anaconda
```


4. Then I had to install a bunch of additional packages, the last one is just to get rid of a warning and can be skipped.
```
conda install cherrypy
conda install omegaconf
conda install tqdm
conda install einops
conda install pytorch-lightning
conda install pandas
conda install transformers
conda install ftfy
conda install kornia
conda install scipy=1.8
```

As for the config.txt file, there should be a config-default.txt that's referenced if config.txt doesn't exist.

**Comment by nmalcolm-mcw** [comment]
> Here's what I had to do to get the code running, performed between steps 2 and 3.
> 
> 1. Install NVIDIAs CUDA for my system, I used the network install after following the workflow.
>    [CUDA Toolkit 11.8 Downloads](https://developer.nvidia.com/cuda-downloads)
> 2. Then I installed pytorch. The site has a nice workflow on what conda command to run for your system. And while I had CUDA version 11.8 installed, pytorch-cuda 11.7 seems to work (pytorch-cuda 11.8 is not released yet). It also has some verification steps further down to ensure it installed correctly, and that CUDA is enabled for the GPU.
>    [PyTorch](https://pytorch.org/get-started/locally/)
> 
> That will get you to the point that it detects your graphics card, however, the program continued to fail for me, so I had to perform some additional steps.
> 
> 3. Added some new channels to conda so I wouldn't have to specify them each time they would be referenced.
> 
> ```
> conda config --env --add channels conda-forge
> conda config --env --add channels anaconda
> ```
> 
> 4. Then I had to install a bunch of additional packages, the last one is just to get rid of a warning and can be skipped.
> 
> ```
> conda install cherrypy
> conda install omegaconf
> conda install tqdm
> conda install einops
> conda install pytorch-lightning
> conda install pandas
> conda install transformers
> conda install ftfy
> conda install kornia
> conda install scipy=1.8
> ```
> 
> As for the config.txt file, there should be a config-default.txt that's referenced if config.txt doesn't exist.

Hi, I'm getting the same error as the people above. I tried the 4 steps outlined above, but I still get:

(dream-factory) C:\Users\njm3\dream-factory>python dream-factory.py --prompt_file prompts/example-standard.prompts
[controller] >>> reading configuration from config.txt...
[controller] >>> starting webserver (http://localhost:8080/) as a background process...
[controller] >>> detected 0 total GPU device(s)...
[controller] >>> ERROR: unable to initialize any GPUs for work; exiting!

Is there something else I should try (and/or is this a case of user error)?

**Comment by rbbrdckybk** [comment]
@Elyssen-1 did you ever figure this out? I'm assuming you have the nvidia driver installed - if so, have you made any changes to your config.txt file?

@MorinTedronai are you still having issues? The config.txt file should be in the root (/dream-factory) directory, not in /stable-diffusion - setup.py should have made a copy of config-default.txt and named it config.txt.

@Pocketsnb did you run setup.py (or see any errors while it was running)? Setup should have installed pytorch of all of the required packages for you.

@Pocketsnb what GPU do you have? And are the nvidia drivers installed? If so, is **USE_GPU_DEVICES = auto** in your config.txt file?

Apologies for the delay in getting back to everyone, I'm currently traveling. Would definitely like to get the bottom of any issue(s) with setup.py if it's not working for everyone so I can make corrections, so please send as much info as possible. If you don't believe setup.py is working properly for you, please try running it in verbose mode (**python setup.py --verbose**) and look for errors in the output if possible!

**Comment by Pocketsnb** [comment]
@nmalcolm-mcw 
Might be a hardware thing, in that the graphics card doesn't support CUDA, that's about the only thing I can think of.

nVidia has a listing of CUDA enabled graphics card at this site:
[CUDA GPUs - Compute Capability](https://developer.nvidia.com/cuda-gpus#compute)
I expanded this table and found my desktop graphics card, so I know it was supported.
[CUDA-Enabled GeForce and TITAN Products](https://developer.nvidia.com/cuda-gpus#collapse4)

You can also try the verification steps on [PyTorch - Windows Verification](https://pytorch.org/get-started/locally/#windows-verification) to see if pytorch installed correctly and if CUDA is available for your graphics card.

**Comment by Pocketsnb** [comment]
@rbbrdckybk , setup.py did not install pytorch or the other packages on execution for me, which I thought was odd. I didn't see any errors during execution.
I'll startup a new environment and follow the default steps with --verbose to see what comes out and post back later.

**Comment by Pocketsnb** [comment]
```
(dream-factory-test) PS F:\dream-factory> python setup.py --verbose

Cloning all required repositories:
Cloning into 'taming-transformers'...
remote: Enumerating objects: 1335, done.
remote: Total 1335 (delta 0), reused 0 (delta 0), pack-reused 1335
Receiving objects: 100% (1335/1335), 409.77 MiB | 10.74 MiB/s, done.
Resolving deltas: 100% (280/280), done.
Cloning into 'CLIP'...
remote: Enumerating objects: 236, done.
remote: Total 236 (delta 0), reused 0 (delta 0), pack-reused 236 eceiving objects: 100% (236/236), 5.91 MiB | 11.80 MiB/Receiving objects: 100% (236/236), 8.92 MiB | 12.26 MiB/s, done.

Resolving deltas: 100% (122/122), done.
Cloning into 'stable-diffusion'...
remote: Enumerating objects: 492, done.
remote: Total 492 (delta 0), reused 0 (delta 0), pack-reused 492Receiving objects:  92% (453/492), 37.61 MiB | 12.52 MiBReceiving objects:  93% (458/492), 37.61 MiB | 12.52 MiB/s
Receiving objects: 100% (492/492), 42.52 MiB | 12.50 MiB/s, done.
Resolving deltas: 100% (212/212), done.
Cloning into 'Real-ESRGAN'...
remote: Enumerating objects: 755, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 755 (delta 5), reused 14 (delta 3), pack-reused 735
Receiving objects: 100% (755/755), 5.37 MiB | 10.04 MiB/s, done.
Resolving deltas: 100% (406/406), done.

Installing Pytorch (this may take a few minutes):

Unable to find executable - try re-running setup with the --shell option, e.g.:
   python setup.py --shell --force
```

After this failed, I deleted the cloned branch and restarted the environment to try with `--shell` and happily that seemed to have fixed the installation issue and I didn't see any other failures in the verbose output. A config.txt was also automatically created, so that preempts another issue I had seen previously where, when running on config-default.txt, the webserver wouldn't stay up. However...
```
[controller] >>> detected 0 total GPU device(s)...
[controller] >>> ERROR: unable to initialize any GPUs for work; exiting!
```
Here's a `conda list --export` of the environment that succeeds and the one that fails on my system, as well as a google doc with a comparison of the packages.
[package-list-success.txt](https://github.com/rbbrdckybk/dream-factory/files/9925504/package-list-success.txt)
[package-list-failure.txt](https://github.com/rbbrdckybk/dream-factory/files/9925505/package-list-failure.txt)
[dream-factory Package Comparison](https://docs.google.com/spreadsheets/d/1sujKGNkHhs33NhD-MgYO25WCNFfVYEPDKhXqFLfIjxo/edit?usp=sharing)

**Comment by Elyssen-1** [comment]
@rbbrdckybk I went with a different repo that seems to be working right away.
None of the solutions above seem to work in my case with a freshly created (dream-factory) conda env.
That being said launching with the (base) env now detects my GPU, I've probably installed something that was missing but does not install on it's own following the installation steps.
I'll attach the env list in case @Pocketsnb can make any sense out of it, if they want to compare mine to theirs.
[package-list-base.txt](https://github.com/rbbrdckybk/dream-factory/files/9944172/package-list-base.txt)
If there are any more logs/lists/steps I can find/do to debug let me know.

**Comment by rbbrdckybk** [comment]
Apologies to everyone that was experiencing this issue, I'm back from traveling and set up a clean environment today to test this. Look like my installer was trying to set up an older version of pytorch that isn't properly supported anymore, causing a non- cuda enabled version to be installed (which won't work with Dream Factory).

It's fixed now. If you were having issues with this before and want to give it another shot, it's best to start with a fresh environment to avoid having to manually uninstall/upgrade things.
