### ISSUE TITLE
Supporting stable-diffusion 2

### ISSUE THREAD

**Issue by relh** [rbbrdckybk/dream-factory#17]
Do you think it will be easy to support stable-diffusion 2? https://github.com/Stability-AI/stablediffusion

I'll try and make a PR if I can get it to work.

**Comment by relh** [comment]
I ran into some annoyances:

- cloning the new stable diffusion and replacing folder is fine
- need to replace some functions in `util.py` and `autoencoder.py` and that's fine
- the only REAL change needed is changing the config yamls to have 1024 instead of 768 (as v2 is higher resolution)
- however, it now hangs after trying to download something and reaching 100%

**Comment by rbbrdckybk** [comment]
Thanks, adding SD 2.0 support is on my list but I haven't had any time to look into it yet (also haven't been that impressed with the base model, but presumably the community will eventually remedy that). Things are pretty crazy around the holidays on my end so it probably won't happen until early next year.

**Comment by rbbrdckybk** [comment]
SD 2.0 is supported in the [latest release](https://github.com/rbbrdckybk/dream-factory/blob/main/CHANGELOG.md#20221206), which essentially uses Automatic1111's repo as the backend.

Recommend a fresh install if you want to try it out!

**Comment by relh** [comment]
![Screenshot from 2022-12-10 10-30-35](https://user-images.githubusercontent.com/3629411/206862724-1badca82-efa3-427e-8d9f-e4f4c555b958.png)

I was able to get it working though I had to install and use --xformers to make everything fit in my GPU memory on a 2080
