### ISSUE TITLE
Wrong Missing Data on Stable Diffusion  

### ISSUE THREAD

**Issue by Wizzzarium** [rbbrdckybk/dream-factory#20]
![image](https://user-images.githubusercontent.com/101677216/207161341-dd35d28e-0920-4336-9238-298431448ea4.png)
If I try to run the dream-factory with both commands it shows me this error. My Stable Diffusion works just fine but if I try to run the dream-factory it shows me an error that something is missing (image). Am I doing something wrong?

(dream-factory) C:\Users\*\dream-factory>python dream-factory.py --prompt_file prompts/example-standard.prompts
Traceback (most recent call last):
  File "C:\Users\*\dream-factory\dream-factory.py", line 30, in <module>
    from torch.cuda import get_device_name, device_count
  File "D:\.coding\anaconda\envs\dream-factory\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "D:\.coding\anaconda\envs\dream-factory\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by rbbrdckybk** [comment]
It looks like Pytorch isn't installed properly - did you run Dream Factory's setup.py? If so, were there any errors?

You can try re-running with the --verbose flag which might let you see more detail:
```
python setup.py --force --verbose
```

**Comment by Wizzzarium** [comment]
It worked but it because I didnt use the installation commands in the right folder. Just had missing things, thank you!
