### ISSUE TITLE
Help with !INPUT_IMAGE

### ISSUE THREAD

**Issue by Wizzzarium** [rbbrdckybk/dream-factory#21]
If i try to put in a basic image (jpg) on my pc with my normal path it says it cant find the picture. Is there something wrong or do you have to add it to a special path due to Anaconda? The error I get is attached.
![image](https://user-images.githubusercontent.com/101677216/207961272-df35c5b6-8568-40f7-bfa2-519e7b7fb625.png)

**Comment by rbbrdckybk** [comment]
Can you please paste the contents of the prompt file that you're trying to use, along with a screenshot of Windows Explorer open to the folder that contains 500.png?

**Comment by Wizzzarium** [comment]
![image](https://user-images.githubusercontent.com/101677216/208115691-e653976b-a2de-41d5-a3d4-3d4f88f4f72a.png)

Prompt File: 


# *****************************************************************************************************

# Dream Factory standard prompt file

# created 2022-12-14 at 21:05:28 via the integrated prompt editor

# *****************************************************************************************************

# these are the default configuration parameters set in your config.txt file

# you may override anything in this section if you wish, otherwise skip down to the [prompts] section(s) below

[config]



!MODE = standard                       # standard mode; queue all possible combinations of [prompts] below

!DELIM = " "							# delimiter to use between prompt sections, default is space

!REPEAT = yes							# repeat when all work finished (yes/no)?



# in standard mode, you may put also embed any of the following config directives into 

# the [prompt] sections below; they'll affect all prompts that follow the directive



!WIDTH = 512							# output image width

!HEIGHT = 512							# output image height

!HIGHRES_FIX = no				        # fix for images significantly larger than 512x512, if enabled uses !STRENGTH setting

!STEPS = 50							# number of steps, more may improve image but increase generation time

!SAMPLER = Euler                      # sampler to use; press ctrl+h for reference

!SAMPLES = 1					      	# number of images to generate per prompt

!SCALE = 7.5							# guidance scale, increase for stricter prompt adherence

!INPUT_IMAGE =	C:\Users\henni\dream-factory\dream-factory\500.png\					# specify an input image to use as a generation starting point

!STRENGTH = 0.75						# strength of input image influence (0-1, with 1 corresponding to least influence)

!CKPT_FILE =                           # model to load, press ctrl+h for reference



# optional integrated upscaling



!USE_UPSCALE = no						# upscale output images?

!UPSCALE_AMOUNT = 2.0					# upscaling factor

!UPSCALE_CODEFORMER_AMOUNT = 0.0		# how visible codeformer enhancement is, 0-1

!UPSCALE_GFPGAN_AMOUNT = 0.0			# how visible gfpgan enhancement is, 0-1

!UPSCALE_KEEP_ORG = no				# keep the original non-upscaled image (yes/no)?



# optional negative prompt



!NEG_PROMPT = 



# *****************************************************************************************************

# prompt section

# *****************************************************************************************************

[prompts]

single pixalated koala looking in camera 





# put your prompts here; one per line

# you may also add additional [prompt] sections below, see 'example-standard.prompts' for details

**Comment by rbbrdckybk** [comment]
Just remove the trailing slash from your !INPUT_IMAGE line - it should look like this:
```
!INPUT_IMAGE = C:\Users\henni\dream-factory\dream-factory\500.png
```

**Comment by Wizzzarium** [comment]
Somehow it still doesnt work, this is the error I get now. 
![image](https://user-images.githubusercontent.com/101677216/208181588-90cb3b0e-ff0d-46a7-a86a-b7622c241691.png)

**Comment by Wizzzarium** [comment]
> Somehow it still doesnt work, this is the error I get now. ![image](https://user-images.githubusercontent.com/101677216/208181588-90cb3b0e-ff0d-46a7-a86a-b7622c241691.png)

Everything else Prompt and Path is still unchanged.

**Comment by rbbrdckybk** [comment]
Oh, it looks like your input file is a .jpg, not a .png file. You need to make sure the extension is correct - should be:
```
!INPUT_IMAGE = C:\Users\henni\dream-factory\dream-factory\500.jpg
```

**Comment by Wizzzarium** [comment]
Sorry man could have noticed that myself. Thanks tho, it works now!
