### ISSUE TITLE
Is SD_LOW_MEMORY gone?

### ISSUE THREAD

**Issue by Nihilentropy-117** [rbbrdckybk/dream-factory#22]
When I attempt to use the low memory card option, it returns
`*** WARNING: prompt file command not recognized: SD_LOW_MEMORY (it will be ignored)! ***
`
I know in ai-art-generator I had to specify !PROCESS = stablediff as well, but "Process" isn't recognized either. I've tried [config] and [prompts]

**Comment by rbbrdckybk** [comment]
Yes, both of those directives have been removed in Dream Factory. If you have a GPU with low VRAM, you can enable the ```--lowvram``` switch in your Auto1111 startup script; Dream Factory will automatically pick it up and use it.

The complete [Dream Factory command reference for .prompt files is here](https://github.com/rbbrdckybk/dream-factory#prompt-file-command-reference).
