### ISSUE TITLE
Feature request: using other samplers besides DDIM

### ISSUE THREAD

**Issue by masonc15** [rbbrdckybk/dream-factory#3]
As most of my images are generated with euler_a, this would be an awesome addition!  Thanks.

**Comment by rbbrdckybk** [comment]
It's actually already implemented for the memory-optimized version (!SD_LOW_MEMORY = yes), I just haven't documented it yet. 

Just throw this into your .prompt file:

**!SAMPLER = euler_a**
_(valid choices = "ddim", "plms","heun", "euler", "euler_a", "dpm2", "dpm2_a", "lms")_

if you're using the faster non-memory optimized version (!SD_LOW_MEMORY = no), then only ddim and plms will work at the moment.

Will leave this open as a reminder to document and get a default value into config.txt and the example prompt files.

**Comment by fillemazendacus** [comment]
Hello!
But it seems it does not use other samplers despite marking it out in promt file as you describe - in terminal under "starting job" and later in gallery under image description still says "sampler: ddim".. Tried to change it to all of others.

**Comment by masonc15** [comment]
I think @fillemazendacus is correct.  I wasn't sure but based off the image results I'm used to, the sampler is definitely not being changed.

**Comment by rbbrdckybk** [comment]
Switching samplers is working properly for me, at least in txt2img with !SD_LOW_MEMORY = yes (img2img and the non-low-memory mode have less samplers available currently).

You can verify by running the below prompt file; I've included my own output below. Keep in mind the differences between the non-ancestral samplers can be subtle, especially with low step counts.

If you're not seeing the same results, please make sure you're up-to-date (you can use **python setup.py --update** for this). If you have the latest code, please paste the results of your test run here so I can investigate.

```
[config]

!MODE = standard
!SD_LOW_MEMORY = yes
!SD_LOW_MEM_TURBO = yes
!REPEAT = no
!DELIM = " "
!WIDTH = 512
!HEIGHT = 512
!STEPS = 40
!SCALE = 7.5
!SAMPLES = 1
!CKPT_FILE =

[prompts]

!SEED = 1

!SAMPLER = euler_a
an illustration of an angry robot

!SAMPLER = euler
an illustration of an angry robot

!SAMPLER = plms
an illustration of an angry robot

!SAMPLER = lms
an illustration of an angry robot

!SAMPLER = ddim
an illustration of an angry robot

!SAMPLER = heun
an illustration of an angry robot

!SAMPLER = dpm2
an illustration of an angry robot

!SAMPLER = dpm2_a
an illustration of an angry robot
```
The output of the prompt file is below:


**ddim:**
![ddim](https://user-images.githubusercontent.com/80607958/196307762-ba67517b-620a-449b-9302-a7c256ebcefa.jpg)

**plms:**
![plms](https://user-images.githubusercontent.com/80607958/196307772-85db280c-5a3f-4f3c-9d00-047489eebe8e.jpg)

**lms:**
![lms](https://user-images.githubusercontent.com/80607958/196307770-82d89d4c-3dc7-4c24-82d2-5c710394aeb6.jpg)

**euler:**
![euler](https://user-images.githubusercontent.com/80607958/196307767-e3775dcc-0c54-4e3b-a973-52cdb5f2b36a.jpg)

**euler_a:**
![euler_a](https://user-images.githubusercontent.com/80607958/196307768-3dabcf14-00d1-4da8-9ed5-ec13bf6f6f60.jpg)

**heun:**
![heun](https://user-images.githubusercontent.com/80607958/196307769-d9b82bb7-a7d1-45db-9b85-bf26845afe37.jpg)

**dpm2:**
![dpm2](https://user-images.githubusercontent.com/80607958/196307764-3d714068-b194-42b7-baa6-8838e79dbfdb.jpg)

**dpm2_a:**
![dpm2_a](https://user-images.githubusercontent.com/80607958/196307765-6c35c4e9-796c-4217-948d-238dc39136b9.jpg)

**Comment by fillemazendacus** [comment]
Hey! Update (not via anaconda (given "try re-running setup with the --shell option" didn't helped there either) but via git bash terminal although) worked for me. Thank you!

**Comment by fillemazendacus** [comment]
Interestingly, it seems that when using the input image, the ddim sampler is automatically selected.

**Comment by rbbrdckybk** [comment]
Yes, currently ddim is the only supported sampler when using img2img. On my list of enhancements to make!

**Comment by rbbrdckybk** [comment]
Just a note that the latest release uses Auto1111's repo as the backend and supports all the same samplers for both txt2img and img2img!
