### ISSUE TITLE
existing device-id commandline params not removed

### ISSUE THREAD

**Issue by yggdrasil75** [rbbrdckybk/dream-factory#31]
if I have --device-id in my commandline params for my primary webui-user.bat, when this copies it, it keeps that and adds a second device-id flag. this appears to result in vram of 1 being used while the processing is split between the 2. should have everything split between them instead.

**Comment by rbbrdckybk** [comment]
Just pushed a fix for this. I actually wrote myself a comment in the code to handle this case when I originally did the auto1111 integration and then forgot about it. Thanks for the reminder!

DF will now ignore any existing user-defined --device-id and/or --port arguments in the auto1111 startup script.
