### ISSUE TITLE
startup issue with more than 1 simultaneous startup

### ISSUE THREAD

**Issue by yggdrasil75** [rbbrdckybk/dream-factory#33]
when you enable multiple servers starting at the same time, the tool will not run. the reason this occurs (as far as I can tell) is that the tool attempts to update venv folder, striking the same file, which leads to the one that is slightly slower crashing silently. what I am doing in an attempt to make a winforms project similar to this to get around the issue is hardlinking a duplicate of the venv folder and pointing to that duplicate. since this is python and going to be on linux, symlinks would probably also work similarly. additionally: just copying the folder will work, or just setting the path without doing anything else will work as well. it will just recreate everything its missing.

**Comment by rbbrdckybk** [comment]
Hey - I'm not sure I understand you fully. Do you mean that there are potential issues if you set GPU_INIT_STAGGER in your config.txt to a value higher than 1? With GPU_INIT_STAGGER = 1, each GPU will wait until the previous GPU has fully loaded Auto1111 before attempting to startup, so there shouldn't be any potential for issues.

Setting GPU_INIT_STAGGER to higher values may indeed cause problems, I've tested it very little with values >1 and always run my own rigs with it set to 1.

**Comment by yggdrasil75** [comment]
yep, that setting. I tried turning it on, and it has a 50/50 chance of failing. after testing on my own, file access collisions on the venv files was the cause, so just setting the venv folder fixes it.
