### ISSUE TITLE
[cuda:0] >>> *** Error response received! *** : 

### ISSUE THREAD

**Issue by eyildiz-ugoe** [rbbrdckybk/dream-factory#37]
No further explanation or anything given. It simply prints this message every time it queries something.  This is the Ubuntu installation I am using.

What's even strange is that the same prompt file works on the installation on Windows.

**Comment by rbbrdckybk** [comment]
Yeah I should really go back and echo the error from Auto1111, although they're not generally useful. 

Easiest way to troubleshoot at the moment is to manually start up Auto1111 with ```--api``` as a startup argument (so on linux, open your Auto1111 ```webui-user.sh```, and add --api to the line that says 'export COMMANDLINE_ARGS=""' and make sure it's uncommented), then wait for it to fully load. Then set Dream Factory to use the same port (7860 by default), so make sure your Dream Factory ```config.txt``` has ```SD_PORT = 7860``` .

When you start Dream Factory, it will find that Auto1111 is already running on that port and automatically use it as long as the --api flag was properly set in your webui-user.sh. This way, you'll be able to watch the Auto1111 console as you use Dream Factory and see the exact errors that Auto1111 is throwing.

Hopefully that helps!
