### ISSUE TITLE
Allow Step count value to be a random range 

### ISSUE THREAD

**Issue by paulm** [rbbrdckybk/dream-factory#38]
Similar to `!MIN_SCALE` - `!MAX_SCALE`, please allow for a variable setting for the Step count. 

Also, consider if it would be simpler to represent random range settings in the same syntax as in the `[prompts 1-3]`. There could be a single `!SCALE =` variable that would allow a fixed value or a range in the form of `!SCALE = [6.0-11.0]`

**Comment by rbbrdckybk** [comment]
Done! Took your suggestion and enabled specifying a random range as:
```
!DIRECTIVE = min - max
```
Will work for !STEPS, !SCALE, and !STRENGTH. The old way will continue to work for !SCALE and !STRENGTH.

**Comment by paulm** [comment]
Excellent. Thank you
