### ISSUE TITLE
job shuts down on me, webserver isn't starting as well.

### ISSUE THREAD

**Issue by vandlol** [rbbrdckybk/dream-factory#4]
job shuts down on me, webserver isn't starting as well.

(dream-factory) PS C:\dream-factory> python .\dream-factory.py
[controller] >>> reading configuration from config.txt...
[controller] >>> starting webserver (http://localhost:8080/) as a background process...
[controller] >>> detected 1 total GPU device(s)...
[controller] >>> initialized worker 'cuda:0': NVIDIA GeForce RTX 2070 SUPER
[controller] >>> No more work in queue; waiting for all workers to finish...
[controller] >>> All work done; pausing server - add some more work via the control panel!
[controller] >>> Server shutdown requested; cleaning up and shutting down...

Did i do something wrong? couldnt find an option to make process idle or something

**Comment by rbbrdckybk** [comment]
Sorry for the delay in responding; did you ever figure this out? The "server shutdown requested" line in the log should only happen at the user's request (via the 'shutdown' button in the web UI, or via ctrl+c / ctrl+break). 

If it's shutting down by itself, something else is going on. Is something else running on port 8080? Try setting **WEBSERVER_CONSOLE_LOG = yes** in your config.txt to see if you get any errors from the webserver on startup.

**Comment by Pocketsnb** [comment]
Same thing was happening to me. Edited config-default.txt to have **WEBSERVER_OPEN_BROWSER = yes**, but it would still shutdown.
Created a copy of **config-default.txt** and renamed it to **config.txt** and the webserver stayed up.
