### ISSUE TITLE
Save metadata of the generated pictures

### ISSUE THREAD

**Issue by PeterL-1111** [rbbrdckybk/dream-factory#43]
This has been helping me a lot but I would like to save the prompts/seed that used to generated each picture, which in A1111 it was easy to do with png saving option. Is there a way to call any API to save metadata into the pictures?

**Comment by rbbrdckybk** [comment]
Generation metadata is saved by default to the .jpg EXIF info. You can see it in any EXIF viewer, including Windows Explorer (right click image, properties, details, check under "comments" field).

![image](https://github.com/rbbrdckybk/dream-factory/assets/80607958/999bcef9-1f7a-4f3a-8e01-73afb4f67107)

**Comment by PeterL-1111** [comment]
Thank you!! That solves my problem!
