### ISSUE TITLE
Seed is drifting

### ISSUE THREAD

**Issue by Koneko349** [rbbrdckybk/dream-factory#49]
I have a standard prompt with the following fields

!CKPT_FILE = all
!SEED = 1178461960

I want to use the same seed for all prompts across all models however I am noticing the seed incrementing by 1 with each new model.

if I switch to random mode the seed increments between images when batch or samples is used. Is it possible to get a flag to keep the seed, increment, decrement, or randomize the seed for each generation?

**Comment by rbbrdckybk** [comment]
That sounds like a bug. The seed should only increment after all the models in the queue have finished a loop. Will take a look next time I have a minute.

**Comment by rbbrdckybk** [comment]
Fixed in the latest. Specific seeds will now only increment after going through the entire model queue.
