### ISSUE TITLE
AMD Radeon Support?

### ISSUE THREAD

**Issue by MPPexcellent** [rbbrdckybk/dream-factory#5]
Hello, love the project. Are there any plans to support AMD GPUs like the Radeon RX580 in the future or should I finally go ahead and buy an NVIDIA GPU?

**Comment by rbbrdckybk** [comment]
No immediate plans to implement support for AMD GPUs, although it's on my list of things to eventually investigate. I actually have a couple old RX580s sitting around myself that I'd love to use for this if possible!
