### ISSUE TITLE
!CKPT_FILE = all no longer working

### ISSUE THREAD

**Issue by Koneko349** [rbbrdckybk/dream-factory#50]
Pulled the new version of dream factory and !CKPT_FILE = all does not appear to work in random mode, the model never changes. It does appear to still be working in standard mode once all of the prompt combinations have been exhausted.

**Comment by rbbrdckybk** [comment]
In your config.txt file, take a look at:
```
RANDOM_QUEUE_SIZE = 
```
Set that to however many images you want DF to produce before moving to the next model in random mode. Default is 50.

**Comment by Koneko349** [comment]
Thanks! I was using batch_size and samples for that previously
