### ISSUE TITLE
Any chance for this to work with Stability Matrix/ComfyUI?

### ISSUE THREAD

**Issue by C-Fu** [rbbrdckybk/dream-factory#54]
Looks mighty impressive, but as I've transitioned to Stability Matrix as well as ComfyUI, I can't help but wonder :)

**Comment by rbbrdckybk** [comment]
ComfyUI has an API, so in theory Dream Factory could be made to work with it, but it'd be a fair amount of work. At the moment, my understanding is that Auto1111 and Comfy basically support roughly the same feature set, and the difference between them is mostly UI/workflow - so I don't see a super compelling reason to support it at this time.

Dream Factory should work alongside whatever tool(s) you currently use just fine, though, assuming you're willing to re-install Auto1111.
