### ISSUE TITLE
Negative prompts to go with positive prompts

### ISSUE THREAD

**Issue by tianshuo** [rbbrdckybk/dream-factory#6]
eg. for people, `((((ugly)))), (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))). (((more than 2 nipples))). out of frame, ugly, extra limbs, gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), (cross-eyed),body out of frame, , (closed eyes), (mutated), (bad body)`

for non-people, something completely else

**Comment by rbbrdckybk** [comment]
You can do that:

[prompts]

!NEG_PROMPT = this will go with the cat prompt below
a photo of a cat

!NEG_PROMPT = this will go with the dog prompt below
a photo of a dog

**Comment by tianshuo** [comment]
This should be written in the document, thank you
