### ISSUE TITLE
[BUG] Create output folders if they don't exist

### ISSUE THREAD

**Issue by tianshuo** [rbbrdckybk/dream-factory#7]
From error `FileNotFoundError: [Errno 2] No such file or directory: 'output/2022-10-18-2022-10-18-prompts-standard/gpu_1'`

**Comment by rbbrdckybk** [comment]
Please paste the entire error chain - I haven't seen this one unless unless interrupting execution with ctrl+c/ctrl+break.

**Comment by tianshuo** [comment]
```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "dream-factory.py", line 143, in run
    new_files = os.listdir(samples_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'output/2022-10-20-2022-10-18-prompts-standard/gpu_4'
```

**Comment by rbbrdckybk** [comment]
Can you provide more context? It looks like you have at least 5 GPUs running - are you on Windows or Linux? Does this problem always occur, or does it run fine for awhile and then you randomly see this happen?

Can you paste the entirety of your log, from startup to where the error occurs if this always occurs? If it's intermittent, can you paste the your log from the beginning to where the first job starts (including every after "starting job #1:")?

If you watch the **output/2022-10-20-2022-10-18-prompts-standard** directory while Dream Factory is running and working on a prompt file, do you see gpu_0, gpu_1, gpu_2, etc sub-directories being created as your GPUs works on images?

**Comment by fillemazendacus** [comment]
I had the same error message when my input image was mistakenly saved as a .tif file instead of a .jpg - change to .jpg solved the problem.
