### ISSUE TITLE
python: can't open file 'scripts_mod/txt2img.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tianshuo** [rbbrdckybk/dream-factory#9]
Fix: symlink `stable_diffusion/scripts` to scripts_mod

**Comment by rbbrdckybk** [comment]
Did your setup complete successfully? You should have a /scripts_mod dir with a txt2img.py file in there.

**Comment by Crimson039** [comment]
My error is similar, saying "python: can't open file 'scripts/txt2img.py': [Errno 2] No such file or directory" after input >python scripts/txt2img.py "description". However, I see a txt2img.py file in the scripts folder (stable-diffusion --> stable-diffusion main --> scripts --> txt2img.py)
